version: '3'
services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  Message_Box:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=messageBox'
      - 'MYSQL_PASSWORD=123456'
      - 'MYSQL_ROOT_PASSWORD=654321'
      - 'MYSQL_USER=little_weakduck'
    ports:
      - '9999:3306'

  my_app:
    image: 'messagebox_java:latest'
    depends_on:
      - Message_Box
    environment:
      - 'DATABASE_HOST=Message_Box'
      - 'DATABASE_PORT=3306'
      - 'DATABASE_NAME=messageBox'
      - 'DATABASE_USER=little_weakduck'
      - 'DATABASE_PASSWORD=123456'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my_app.rule=PathPrefix(`/`)"
      - "traefik.http.routers.my_app.entrypoints=web"
